FrontEnd/Controllers/PersonasFisicasController.cs
using FrontEnd.Servicios;
using Microsoft.AspNetCore.Mvc;
using FrontEnd.Models;
using Microsoft.AspNetCore.Identity;

namespace FrontEnd.Controllers
{
    public class PersonasFisicasController : Controller
    {
        private readonly IRepositorioPersonasFisicas repositorioPersonasFisicas;
        private readonly HttpContext httpContext;
        private readonly int _RegistrosPorPagina = 20;
        private PaginadorGenerico<PersonaFisica> _Paginador;
        public PersonasFisicasController(IRepositorioPersonasFisicas repositorioPersonasFisicas, IHttpContextAccessor httpContextAccessor)
        {
            this.repositorioPersonasFisicas = repositorioPersonasFisicas;
            httpContext = httpContextAccessor.HttpContext;
        }
        public async Task<IActionResult> Index(int pagina = 1)
        {


            var personasAll = await repositorioPersonasFisicas.GetPersonasFisicas();
            int _TotalRegistros = personasAll.Count;
            var _TotalPaginas = (int)Math.Ceiling((double)_TotalRegistros / _RegistrosPorPagina);
           var personas = personasAll.OrderBy(x => x.IdPersonaFisica).Skip((pagina - 1) * _RegistrosPorPagina).Take(_RegistrosPorPagina).ToList();
            _Paginador = new PaginadorGenerico<PersonaFisica>()
            {
                RegistrosPorPagina = _RegistrosPorPagina,
                TotalRegistros = _TotalRegistros,
                TotalPaginas = _TotalPaginas,
                PaginaActual = pagina,
                Resultado = personas
            };
            //PersonaFisica persona = new PersonaFisica() { IdPersonaFisica=4, Activo = true,ApellidoMaterno = "MVc",Rfc="DERD970403E94",Nombre ="DAvid",ApellidoPaterno="delgado",UsuarioAgrega=2};
            //var result = repositorioPersonasFisicas.DeletePersonaFisica(4);
            return View(_Paginador);
        }
        public async Task<IActionResult> Crear()
        {
            var personas = await repositorioPersonasFisicas.GetPersonasFisicas();

            //PersonaFisica persona = new PersonaFisica() { IdPersonaFisica=4, Activo = true,ApellidoMaterno = "MVc",Rfc="DERD970403E94",Nombre ="DAvid",ApellidoPaterno="delgado",UsuarioAgrega=2};
            //var result = repositorioPersonasFisicas.DeletePersonaFisica(4);
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Crear(PersonaFisica persona)
        {
            persona.FechaRegistro = DateTime.Today;

            var userId = httpContext.User.Claims.First().Value;
            persona.UsuarioAgrega = int.Parse(userId);
            await repositorioPersonasFisicas.PostPersonaFisica(persona);

            //PersonaFisica persona = new PersonaFisica() { IdPersonaFisica=4, Activo = true,ApellidoMaterno = "MVc",Rfc="DERD970403E94",Nombre ="DAvid",ApellidoPaterno="delgado",UsuarioAgrega=2};
            //var result = repositorioPersonasFisicas.DeletePersonaFisica(4);
            return RedirectToAction("Index");
        }
        
        public async Task<IActionResult> Eliminar(int id)
        {
            
            await repositorioPersonasFisicas.DeletePersonaFisica(id);

           
            return RedirectToAction("Index");
        }

        public IActionResult Editar(int id)
        {
            
            ViewBag.Id = id;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> PutPersonaFisica(PersonaFisica persona,int id)
        {
            await repositorioPersonasFisicas.PutPersonaFisica(id, persona);
            return RedirectToAction("index");
        }

        public IActionResult Consultar()
        {
            
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Mostrar(PersonaFisica persona)
        {
           var result =  await repositorioPersonasFisicas.GetPersonaFisica(persona.Rfc);
         
            return View(result);
        }
    }
}

FrontEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FrontEnd</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FrontEnd.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FrontEnd</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reportes" asp-action="Index">Reportes</a>
                        </li>
                        
                        <li class="nav-item dropdown  text-dark">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Personas Fisicas
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" asp-controller="PersonasFisicas" asp-action="Index">Todas las Personas Fisicas</a></li>
            <li><a class="dropdown-item" asp-controller="PersonasFisicas" asp-action="Crear">Registrar Nueva</a></li>
            <li><a class="dropdown-item" asp-controller="PersonasFisicas" asp-action="Consultar">Consultar</a></li>
          </ul>
        </li>

                    </ul>
                    <partial name="_LinksLogin"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FrontEnd 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FrontEnd/Views/Shared/_LinksLogin.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Usuario> SignInManager

    <ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <span class="nav-link text-dark"> Hola, @User.Identity.Name </span>
        </li>
        <li class="nav-item">
            <form class="form-inline" asp-action="logout" asp-controller="usuarios">
                <button type="submit" class="nav-link btn btn-link text-dark">
                    Logout
                </button>
            </form>
        </li>
    }else{
        
        <li class="nav-item">
        <a class="nav-link dark-text" asp-controller="usuarios" asp-action="Registro">Registro</a>
    </li>
    <li class="nav-item">
        <a class="nav-link dark-text" asp-controller="usuarios" asp-action="Login">Login</a>
    </li>
    }

</ul>